FROM golang:1.12.6
LABEL maintainer "[my name]"
WORKDIR /go/src
ENV GO111MODULE=on
# RUN apt-get update -qq && \
    # apt-get install -y mysql-client vim && \
    # mkdir /go/src /go/pkg /go/bin && \
    # go mod download && \
    # sh ./init.sh
# CMD ["go", "run", "main.go"]